Prepend local include paths in CFLAGS to avoid conflict with system wide includes
CFLAGS could contain system wide include paths which might conflict
with our filenames. So make sure that our local directories are first
in the search order.

Example with conflicting profile.h from kerberos:

tvheadend-4.2.5/src/dvr/dvr.h:27:
/usr/local/include/profile.h:24:28: error: typedef redefinition with
different types ('struct _profile_t *' vs 'struct profile')
typedef struct _profile_t *profile_t;
                           ^
tvheadend-4.2.5/src/profile.h:147:3:
note: previous definition is here
} profile_t;

Reported by:	Frank Razenberg <frank@zzattack.org>