sysutils/docker-engine: Fix buildkit because Unmount() syscall on FreeBSD does not support MNT_DETACH It seems to be a Linuxism to lazy unmount a filesystem. Instead use the Windows version which does not pass any additional flags to Unmount().
The build error was:
vendor/github.com/moby/buildkit/snapshot/localmounter_unix.go:17:38: undefined: syscall.MNT_DETACH